### ISSUE TITLE
Generate logs

### ISSUE THREAD

**Issue by yuxiang-zhang** [Solunra/SOEN390-team11#10]
# User Story
As a DevOps engineer, I want to get logs so that I can debug the system more efficiently. 
I should see the id and message of the log and be able to download the content as a CSV file.

# Tasks

- [x] Orders Log UI #81

- [x] Logging System #82 & #84

- [ ] Add Log functionality to all system components #83

- [x] Add UI for admins #86
