### ISSUE TITLE
Define, Order and Track Raw Materials and Final Product  

### ISSUE THREAD

**Issue by isratnoor** [Solunra/SOEN390-team11#14]
# User Story
As a user, I would like to define, order and track raw materials and products, so that I can create/assemble my own product. 

# Related Tasks
- [x] Define Raw Materials #55

- [x] Define Final Product #56

- [x] Order Custom Products #57

- [x] Order raw material #66 

- [x] Update Products, Parts, Materials #58
