### ISSUE TITLE
Follow Costs

### ISSUE THREAD

**Issue by yuxiang-zhang** [Solunra/SOEN390-team11#8]
# User Story
As a financial officer, I want to follow all Accounts Payable, Accounts Receivable, and Cost/Charge Number so that I can monitor and manage the budget and perform cost-benefit analysis. 

# Tasks

- [x] Relate Order and User #78

- [x] Add Payment Information #79

- [x] Order Information UI #80

- [x] Follow Cost UI #88
