### ISSUE TITLE
Connect to production machinery

### ISSUE THREAD

**Issue by yuxiang-zhang** [Solunra/SOEN390-team11#9]
# User Story
As a user, I want to monitor and/or control the production machinery so that I can easily oversee the production equipment and its work progress. 

# Related Tasks

- [x] Define Product Machinery #52

- [x] Machinery Actions #63

  - [x] Support Timing for Product Machinery #53

- [x] Product Machinery UI #54
